Log uncaught source-mapped errors to the console
cloudflare/miniflare pull request #446
Opened 2022-11-23 18:28 UTC by mrbbot

Previously, errors _thrown_ using the `MF-Experimental-Error-Stack` header were only shown in a pretty-error page. This PR logs those errors with source-maps applied to the console too, using the `source-map-support` package. This simplifies our code, and also means we don't need to touch internal Youch methods, as the errors we pass to Youch are already source-mapped.

2022-11-23 18:29 UTC, JacobMGEvans approved these changes

2022-11-24 11:17 UTC, penalosa commented on packages/tre/src/plugins/core/errors/callsite.ts
> +// Adapted from `node-stack-trace`:
How much is this adapted? Why do we need this _and_ the source-map stuff?

2022-11-24 15:03 UTC, penalosa requested changes

2022-11-24 15:03 UTC, penalosa commented on packages/tre/src/plugins/core/errors/sourcemap.ts
> +        assert.fail(`Unexpected retrieveFile(${JSON.stringify(file)}) call`);
Is the `JSON.stringify` needed if `file` is of type `string`? (and if it isn't can it be typed as `unknown`?)

2022-11-30 09:42 UTC, penalosa approved these changes

2022-11-30 09:44 UTC, merged