[Miniflare 3] Re-implement D1 gateway using new storage system
cloudflare/miniflare pull request #563
Opened 2023-04-28 16:09 UTC by mrbbot

This PR builds on https://github.com/cloudflare/miniflare/pull/555, and re-implements the D1 gateway using the new storage system. This also brings forward changes #533 and #544 from Miniflare 2, fixing those issues in Miniflare 3 as well. 🙂 

Closes DEVX-591

2023-05-02 14:16 UTC, JacobMGEvans approved these changes
Refactor looks great

2023-05-04 11:48 UTC, penalosa requested changes
Looks good!

2023-05-04 11:48 UTC, penalosa commented on packages/tre/src/plugins/d1/gateway.ts
> +import { Database as DatabaseType } from "better-sqlite3";
`import type`

2023-05-04 11:48 UTC, penalosa commented on packages/tre/src/plugins/d1/gateway.ts
> -function returnsData(stmt: Statement): boolean {
Does `columns()` no longer fail in this case?

2023-05-04 11:48 UTC, penalosa commented on packages/tre/src/storage2/sql.ts
> +  prepare<Params = any[], SingleResult = unknown>(
`unknown[]`?

2023-05-09 14:05 UTC, merged