[Miniflare 3] Trust CA root certificates on Windows and `NODE_EXTRA_CA_CERTS`
cloudflare/miniflare pull request #587
Opened 2023-05-23 12:34 UTC by mrbbot

`workerd`'s `trustBrowserCas` uses `SSL_CTX_set_default_verify_paths()` to enable the system trust store. Unfortunately, this doesn't work on Windows, meaning any HTTPS `fetch()` would fail, with an `unable to get local issuer certificate` error. This PR passes the root certificates from Node's bundled CA store to `workerd` as `trustedCertificates` on Windows.

Wrangler also passes the Cloudflare root certificate using the `NODE_EXTRA_CA_CERTS` environment variable. This PR also loads CA certs from this variable, fixing HTTPS `fetch()`s with WARP enabled. This can also be used for trusting self-signed certificates.

Closes https://github.com/cloudflare/workers-sdk/issues/3264
Closes https://github.com/cloudflare/workers-sdk/issues/3218

2023-05-23 23:11 UTC, TheDevMinerTV commented
Please add a changeset so that this can get released in the next patch release. (This is blocking my teams development flow because we can't start miniflare locally.)

2023-05-23 23:12 UTC, TheDevMinerTV requested changes
Please add a changeset so that this can get released in the next patch release. (This is blocking my teams development flow because we can't start miniflare locally.)

2023-05-26 09:45 UTC, merged

2023-07-23 23:40 UTC, kentonv commented on packages/miniflare/src/plugins/core/index.ts
> +    trustedCertificates.push(extra);
This is loading the entire bundle and passing it to workerd as if it were a single certificate. You need to split the bundle into individual certs and add each one to the list here.

2023-07-23 23:42 UTC, kentonv commented on packages/miniflare/src/plugins/core/index.ts
> +    trustedCertificates.push(extra);
(Or maybe we could add a new config option that expects a bundle as a single file, but we'd still have to add some parsing logic on the workerd side to handle that.)